background #060805
foreground #c5c8c6
selection_background #a1b78f
selection_foreground #c5c8c6

active_tab_foreground   #eee
active_tab_background   #82a471
inactive_tab_foreground #98adbf
inactive_tab_background #000

# THE COLOR TABLE
color0 #282a2e
color8 #373b41

color1 #943030
color9 #c46262

color2  #82a471
color10 #90bd68

color3  #d2c647
color11 #f0d474

color4  #1844f2
color12 #81a2be

color5  #85678f
color13 #b294bb

color7  #dddddd
color15 #ffffff
