shell /usr/bin/bash

editor vim

#
linux_display_server x11

#SHELL
shell_integration enabled

# MODIFIER
kitty_mod ctrl+shift

# THEME
include greenish-theme.conf

# FONTS

font_family	 family="JetBrainsMono Nerd Font Mono"
bold_font 	 family='JetBrainsMono Nerd Font Mono' style=Bold
italic_font 	 auto
bold_italic_font auto

font_size 10

# BACKGROUND

background_blur 2
background_opacity 0.7
background_image none
dynamic_background_opacity no

# LAYOUT

enabled_layouts tall,*

# WINDOWS

windows_margin_width 0
confirm_os_window_close 0

# CURSOR

cursor #cccccc
cursor_text_color #111111

cursor_shape beam
cursor_shape_unfocused underline
cursor_beam_thickness 2.0
cursor_underline_thickness 2.5

cursor_blink_interval -1
cursor_stop_blinking_after 6.0

cursor_trail 0
cursor_trail_decay 0.1 0.6
cursor_trail_start_threshold 2
cursor_trail_color none 


# SCROLLBACK
scrollback_lines 500
scrollbar scrolled
scrollbar_interactive yes

# MOUSE
mouse_hide_wait 1.3

# URLS
rl_color #ffffff
url_style curly
url_prefixes file ftps git https kitty mailto ssh
detect_urls yes
show_hyperlink_targets alt

# COPY AND PASTE

copy_on_select yes
clipboard_max_size 300
##copy_on_select a1
##map shift+cmd+v paste_from_buffer a1

# PERFORMANCE
sync_to_monitor no

# TAB BAR

#tab_bar_edge bottom
#tab_bar_style powerline
#tab_powerline_style slanted
#tab_title_max_length 15
#tab_bar_align left
#tab_bar_min_tabs 1
#active_tab_font_style   bold-italic
#inactive_tab_font_style normal

#REMOTE CONTROL
#
allow_remote_control no
