#!/bin/sh

WALLDIR="$HOME/Pictures/Wallpapers"
XINIT="$HOME/.xinitrc"

printf "Wallpaper name (include extension): "
read -r wallpaper

FILE="$WALLDIR/$wallpaper"

if [ ! -f "$FILE" ]; then
    printf "Error: '%s' does not exist.\n" "$FILE"
    exit 1
fi

sed -i "s|^feh --bg-fill .*|feh --bg-fill $FILE|" "$XINIT"

feh --bg-fill "$FILE"

printf "Wallpaper changed to '%s' and .xinitrc updated.\n" "$wallpaper"
