#!/bin/sh

status=$(playerctl status 2>/dev/null)
if [ "$status" != "Playing" ]; then
    printf "  N/A"
    exit
fi

artist=$(playerctl metadata --format '{{ artist }}' 2>/dev/null)
title=$(playerctl metadata --format '{{ title }}' 2>/dev/null)

if [ -z "$artist" ] || [ -z "$title" ]; then
    printf "  N/A"
    exit
fi

max=45

full="$title - $artist"
if [ "${#full}" -gt "$max" ]; then
    full=$(printf "%s" "$full" | cut -c1-"$max")
    full="${full}..."
fi

printf "  %s" "$full"
